<?php

return [
    'PAGE_SIZE' => 10,
    'ACCEPT_IMAGE_TYPES' => 'image/gif,image/png,image/jpeg',

    'DEFAULT' => [
        'ICON' => 'images/favicon.png',
        'LOGO' => 'images/logo.png',
        'AVATAR' => 'images/avatar.png',
        'LOGIN_BG' => 'images/login_bg.jpg',
        'CLUB_LOGO' => 'images/club_logo.jpg',
    ],
    'UPLOAD' => [
        'LOGO_ICON' => 'uploads/app',
        'CLUB_LOGO' => 'uploads/clubs',
    ],
    'FIELD_TYPE' => [
        'string' => 0,
        'number' => 1,
        'boolean' => 2,
        'date' => 3,
        'single_choice' => 4,
        'multi_choice' => 5,
        'data_source' => 6,
    ],
    'FIELD_TYPE_ARRAY' => [
        0 => 'String',
        1 => 'Number',
        2 => 'Boolean',
        3 => 'Date',
        4 => 'Single Choice',
        5 => 'Multi Choice',
        6 => 'Data Source',     
    ],
    'LOCALE_TABS' => [
        'validation',
        'auth',
        'passwords',
        'datatables',
        'email',
        'layouts',
        'home',
        'translations',
        'members',
        'field_groups',
        'fields'
    ],
    'PROFILE_TABS' => [
        'info' => 'info',
        'avatar' => 'avatar',
        'password' => 'password',
    ],
    'PROFILE_TABS' => [
        'info' => 'info',
        'avatar' => 'avatar',
        'password' => 'password',
    ],
    'CONFIG_KEY' => [
        'SITE_LOGO' => 'site_logo',
        'SITE_FAVICON' => 'site_favicon',
        'LOGIN_IMAGE' => 'login_image',
        'DEFAULT_AVATAR_IMAGE' => 'default_avatar_image',
    ],
    'SYSTEM_PERMISSIONS' => [
        'assets_view' => 'assets_view',
        'assets_manage' => 'assets_manage',
        'translations_view' => 'translations_view',
        'translations_manage' => 'translations_manage',
        'groups_view' => 'groups_view',
        'groups_manage' => 'groups_manage',
        'users_view' => 'users_view',
        'users_manage' => 'users_manage',
        'payment_gateway_view' => 'payment_gateway_view',
        'payment_gateway_manage' => 'payment_gateway_manage',
    ],
    'ORG_PERMISSIONS' => [
        'custom_fields_view' => 'custom_fields_view',
        'custom_fields_manage' => 'custom_fields_manage',
        'clubs_view' => 'clubs_view',
        'clubs_create' => 'clubs_create',
        'clubs_edit' => 'clubs_edit',
        'clubs_delete' => 'clubs_delete',
        'members_view' => 'members_view',
        'members_create' => 'members_create',
        'members_edit' => 'members_edit',
        'members_delete' => 'members_delete',
        'payments_view' => 'payments_view',
        'payments_create' => 'payments_create',
        'payments_edit' => 'payments_edit',
        'payments_delete' => 'payments_delete',
        'report_clubs' => 'report_clubs',
        'report_members' => 'report_members',
        'report_payments' => 'report_payments',
    ],
     'PLACEHOLDER_TYPE' =>[
        'choose' => '--Choose--',
     ],
    'AIRCRAFT_TYPE' => [
        'HANGGLIDER' => 'Hangglider',
        'PPG' => 'PPG',
        'TANDEM_PG' => 'Tandem PG',
        'PARAGLIDER' => 'Paraglider',
        'PHG' => 'PHG',
        'TANDEM HG' => 'Tandem HG',
        'KLASSE_P' => 'Klasse P',
    ],
];

